/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_FaceDetector */

#ifndef _Included_com_seeta_sdk_FaceDetector
#define _Included_com_seeta_sdk_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_construct__Lcom_seeta_sdk_SeetaModelSetting_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_construct__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    Detect
 * Signature: (Lcom/seeta/sdk/SeetaImageData;)[Lcom/seeta/sdk/SeetaRect;
 */
JNIEXPORT jobjectArray JNICALL Java_com_seeta_sdk_FaceDetector_Detect
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    set
 * Signature: (Lcom/seeta/sdk/FaceDetector/Property;D)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDetector_set
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     com_seeta_sdk_FaceDetector
 * Method:    get
 * Signature: (Lcom/seeta/sdk/FaceDetector/Property;)D
 */
JNIEXPORT jdouble JNICALL Java_com_seeta_sdk_FaceDetector_get
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
