/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_QualityOfLBN */

#ifndef _Included_com_seeta_sdk_QualityOfLBN
#define _Included_com_seeta_sdk_QualityOfLBN
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_QualityOfLBN
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfLBN_construct__Lcom_seeta_sdk_SeetaModelSetting_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_QualityOfLBN
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfLBN_construct__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_seeta_sdk_QualityOfLBN
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfLBN_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_QualityOfLBN
 * Method:    Detect
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;[I[I[I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfLBN_Detect
  (JNIEnv *, jobject, jobject, jobjectArray, jintArray, jintArray, jintArray);

/*
 * Class:     com_seeta_sdk_QualityOfLBN
 * Method:    set
 * Signature: (Lcom/seeta/sdk/QualityOfLBN/Property;D)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfLBN_set
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     com_seeta_sdk_QualityOfLBN
 * Method:    get
 * Signature: (Lcom/seeta/sdk/QualityOfLBN/Property;)D
 */
JNIEXPORT jdouble JNICALL Java_com_seeta_sdk_QualityOfLBN_get
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
