/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_QualityOfIntegrity */

#ifndef _Included_com_seeta_sdk_QualityOfIntegrity
#define _Included_com_seeta_sdk_QualityOfIntegrity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_QualityOfIntegrity
 * Method:    construct
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfIntegrity_construct__
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_QualityOfIntegrity
 * Method:    construct
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfIntegrity_construct__FF
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_seeta_sdk_QualityOfIntegrity
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_QualityOfIntegrity_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_QualityOfIntegrity
 * Method:    checkCore
 * Signature: (Lcom/seeta/sdk/SeetaImageData;Lcom/seeta/sdk/SeetaRect;[Lcom/seeta/sdk/SeetaPointF;[F)I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_QualityOfIntegrity_checkCore
  (JNIEnv *, jobject, jobject, jobject, jobjectArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
