/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_FaceAntiSpoofing */

#ifndef _Included_com_seeta_sdk_FaceAntiSpoofing
#define _Included_com_seeta_sdk_FaceAntiSpoofing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_construct__Lcom_seeta_sdk_SeetaModelSetting_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_construct__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_construct__Ljava_lang_String_2Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    PredictCore
 * Signature: (Lcom/seeta/sdk/SeetaImageData;Lcom/seeta/sdk/SeetaRect;[Lcom/seeta/sdk/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_PredictCore
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    PredictVideoCore
 * Signature: (Lcom/seeta/sdk/SeetaImageData;Lcom/seeta/sdk/SeetaRect;[Lcom/seeta/sdk/SeetaPointF;)I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_PredictVideoCore
  (JNIEnv *, jobject, jobject, jobject, jobjectArray);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    ResetVideo
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_ResetVideo
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    GetPreFrameScore
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_GetPreFrameScore
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    SetVideoFrameCount
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_SetVideoFrameCount
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    GetVideoFrameCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_GetVideoFrameCount
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    SetThreshold
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_SetThreshold
  (JNIEnv *, jobject, jfloat, jfloat);

/*
 * Class:     com_seeta_sdk_FaceAntiSpoofing
 * Method:    GetThreshold
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceAntiSpoofing_GetThreshold
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
