/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_EyeStateDetector */

#ifndef _Included_com_seeta_sdk_EyeStateDetector
#define _Included_com_seeta_sdk_EyeStateDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_EyeStateDetector
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_EyeStateDetector_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_EyeStateDetector
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_EyeStateDetector_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_EyeStateDetector
 * Method:    DetectCore
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;[I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_EyeStateDetector_DetectCore
  (JNIEnv *, jobject, jobject, jobjectArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
