/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_FaceDatabase */

#ifndef _Included_com_seeta_sdk_FaceDatabase
#define _Included_com_seeta_sdk_FaceDatabase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDatabase_construct__Lcom_seeta_sdk_SeetaModelSetting_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;II)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDatabase_construct__Lcom_seeta_sdk_SeetaModelSetting_2II
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDatabase_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    SetLogLevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceDatabase_SetLogLevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    GetCropFaceWidthV2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceDatabase_GetCropFaceWidthV2
  (JNIEnv *, jclass);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    GetCropFaceHeightV2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceDatabase_GetCropFaceHeightV2
  (JNIEnv *, jclass);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    GetCropFaceChannelsV2
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceDatabase_GetCropFaceChannelsV2
  (JNIEnv *, jclass);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    CropFaceV2
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;Lcom/seeta/sdk/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_FaceDatabase_CropFaceV2
  (JNIEnv *, jclass, jobject, jobjectArray, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Compare
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;)F
 */
JNIEXPORT jfloat JNICALL Java_com_seeta_sdk_FaceDatabase_Compare
  (JNIEnv *, jobject, jobject, jobjectArray, jobject, jobjectArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    CompareByCroppedFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;Lcom/seeta/sdk/SeetaImageData;)F
 */
JNIEXPORT jfloat JNICALL Java_com_seeta_sdk_FaceDatabase_CompareByCroppedFace
  (JNIEnv *, jobject, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Register
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_Register
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    RegisterByCroppedFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_RegisterByCroppedFace
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Delete
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceDatabase_Delete
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDatabase_Clear
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Count
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_Count
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Query
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_Query__Lcom_seeta_sdk_SeetaImageData_2_3Lcom_seeta_sdk_SeetaPointF_2
  (JNIEnv *, jobject, jobject, jobjectArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Query
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;[F)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_Query__Lcom_seeta_sdk_SeetaImageData_2_3Lcom_seeta_sdk_SeetaPointF_2_3F
  (JNIEnv *, jobject, jobject, jobjectArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    QueryByCroppedFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_QueryByCroppedFace__Lcom_seeta_sdk_SeetaImageData_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    QueryByCroppedFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[F)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_QueryByCroppedFace__Lcom_seeta_sdk_SeetaImageData_2_3F
  (JNIEnv *, jobject, jobject, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    QueryTop
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;J[J[F)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_QueryTop
  (JNIEnv *, jobject, jobject, jobjectArray, jlong, jlongArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    QueryTopByCroppedFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;J[J[F)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_QueryTopByCroppedFace
  (JNIEnv *, jobject, jobject, jlong, jlongArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    QueryAbove
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;FJ[J[F)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_QueryAbove
  (JNIEnv *, jobject, jobject, jobjectArray, jfloat, jlong, jlongArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    QueryAboveByCroppedFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;FJ[J[F)J
 */
JNIEXPORT jlong JNICALL Java_com_seeta_sdk_FaceDatabase_QueryAboveByCroppedFace
  (JNIEnv *, jobject, jobject, jfloat, jlong, jlongArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    RegisterParallel
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;[J)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDatabase_RegisterParallel
  (JNIEnv *, jobject, jobject, jobjectArray, jlongArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    RegisterByCroppedFaceParallel
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[J)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDatabase_RegisterByCroppedFaceParallel
  (JNIEnv *, jobject, jobject, jlongArray);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Join
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceDatabase_Join
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Save
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_FaceDatabase_Save
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_seeta_sdk_FaceDatabase
 * Method:    Load
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_FaceDatabase_Load
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
