/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_FaceRecognizer */

#ifndef _Included_com_seeta_sdk_FaceRecognizer
#define _Included_com_seeta_sdk_FaceRecognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceRecognizer_construct__Lcom_seeta_sdk_SeetaModelSetting_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    construct
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceRecognizer_construct__Ljava_lang_String_2Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jstring, jint);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceRecognizer_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    GetCropFaceWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceRecognizer_GetCropFaceWidthV2
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    GetCropFaceHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceRecognizer_GetCropFaceHeightV2
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    GetCropFaceChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceRecognizer_GetCropFaceChannelsV2
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    GetExtractFeatureSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_FaceRecognizer_GetExtractFeatureSize
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    CropFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;Lcom/seeta/sdk/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_FaceRecognizer_CropFaceV2
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    ExtractCroppedFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_FaceRecognizer_ExtractCroppedFace
  (JNIEnv *, jobject, jobject, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    Extract
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_FaceRecognizer_Extract
  (JNIEnv *, jobject, jobject, jobjectArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    CalculateSimilarity
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_seeta_sdk_FaceRecognizer_CalculateSimilarity
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    set
 * Signature: (Lcom/seeta/sdk/FaceRecognizer/Property;D)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_FaceRecognizer_set
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     com_seeta_sdk_FaceRecognizer
 * Method:    get
 * Signature: (Lcom/seeta/sdk/FaceRecognizer/Property;)D
 */
JNIEXPORT jdouble JNICALL Java_com_seeta_sdk_FaceRecognizer_get
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
