/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_GenderPredictor */

#ifndef _Included_com_seeta_sdk_GenderPredictor
#define _Included_com_seeta_sdk_GenderPredictor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_GenderPredictor_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_GenderPredictor_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    GetCropFaceWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_GenderPredictor_GetCropFaceWidth
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    GetCropFaceHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_GenderPredictor_GetCropFaceHeight
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    GetCropFaceChannels
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_seeta_sdk_GenderPredictor_GetCropFaceChannels
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    CropFace
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;Lcom/seeta/sdk/SeetaImageData;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_GenderPredictor_CropFace
  (JNIEnv *, jobject, jobject, jobjectArray, jobject);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    PredictGenderCore
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_GenderPredictor_PredictGenderCore
  (JNIEnv *, jobject, jobject, jintArray);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    PredictGenderWithCropCore
 * Signature: (Lcom/seeta/sdk/SeetaImageData;[Lcom/seeta/sdk/SeetaPointF;[I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_GenderPredictor_PredictGenderWithCropCore
  (JNIEnv *, jobject, jobject, jobjectArray, jintArray);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    set
 * Signature: (Lcom/seeta/sdk/GenderPredictor/Property;D)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_GenderPredictor_set
  (JNIEnv *, jobject, jobject, jdouble);

/*
 * Class:     com_seeta_sdk_GenderPredictor
 * Method:    get
 * Signature: (Lcom/seeta/sdk/GenderPredictor/Property;)D
 */
JNIEXPORT jdouble JNICALL Java_com_seeta_sdk_GenderPredictor_get
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
