/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_seeta_sdk_MaskDetector */

#ifndef _Included_com_seeta_sdk_MaskDetector
#define _Included_com_seeta_sdk_MaskDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_seeta_sdk_MaskDetector
 * Method:    construct
 * Signature: (Lcom/seeta/sdk/SeetaModelSetting;)V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_MaskDetector_construct
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_seeta_sdk_MaskDetector
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_seeta_sdk_MaskDetector_dispose
  (JNIEnv *, jobject);

/*
 * Class:     com_seeta_sdk_MaskDetector
 * Method:    detect
 * Signature: (Lcom/seeta/sdk/SeetaImageData;Lcom/seeta/sdk/SeetaRect;[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_seeta_sdk_MaskDetector_detect
  (JNIEnv *, jobject, jobject, jobject, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
